### ISSUE TITLE
gas fee needs to be checked

### ISSUE THREAD

**Issue by jorijnsmit** [GalloDaSballo/fair-selling#1]
i believe whenever `orderData` is passed, more checks are required to make sure the `orderData` is not malicious:
- `require(orderData.receiver == address(this));`
- `orderData.feeAmount` needs to be <= 10% of `orderData.sellAmount` or something?
- `orderData.kind` needs to be `KIND_SELL`

https://github.com/GalloDaSballo/fair-selling/blob/21a04df45efce2d6e662025d43c34738a767c7a4/contracts/BVECVXBribesProcessor.sol#L110-L112

**Comment by GalloDaSballo** [comment]
Addresed by 8671de07ea20e5d4e552cb9a28650f8fc3dfbdb7
