### ISSUE TITLE
`timeHasExpired` will only be >14 days for a very short amount of time

### ISSUE THREAD

**Issue by jorijnsmit** [GalloDaSballo/fair-selling#2]
https://github.com/GalloDaSballo/fair-selling/blob/6c8fff0f44309e5c81ec19ad6fc77069f5d4ffa1/contracts/VotiumBribesProcessor.sol#L77-L82

still not convinced of this logic:
- round x just finished. bribes are claimed; strat notifies processor, `lastBribeAction` is set
- random user gets impatient and calls ragequit. it reverts (as expected); `timeHasExpired` is false: `block.timestamp` is still smaller than `lastBribeAction + MAX_MANAGER_IDLE_TIME`
- manager fails to swap bribes for the whole duration of round x+1
- [very small window here where ragequit can be called]
- bribes for round x+1 are claimed; strat notifies processor, `lastBribeAction` is set
- random user gets impatient and calls ragequit. it reverts (unexpected behaviour); `timeHasExpired` is only false because `lastBribeAction` got reset again for the new round.

**`timeHasExpired` is only >14 until there is a new bribe claim, because the new bribe claim will reset `lastBribeAction`**

one solution could be to store more data on round numbers, calc days from a certain point, assume rounds are always 14\*24\*60\*60 seconds, etc. lots of ugly custom logic imo.

instead, what if the strategy 'ragequits' on a new bribe claim? ie, when the strat claims bribes (>0) and finds that there are still tokens in the processor, it drains these to the tree first?

**Comment by GalloDaSballo** [comment]
The only rational alternative given the RQ timer would be to set the timer to just 7 / 13 days after the bribes where claimed.
Giving a day or more of grace period while effectively making no particular difference in terms of time to process the bribes.

What do you think?

PS: Yes I'm trying to avoid tracking the balances in the contract, it's highly likely it's going to be a lot of effort

**Comment by jorijnsmit** [comment]
sounds like decreasing it to 7 days is the best option here.

**Comment by GalloDaSballo** [comment]
As discussed we're leaving it to 10 days as fair medium, 7 days probably ideal but ultimately more than 24 hr to rage quit should be more than plenty given how simple the rq process is
