### ISSUE TITLE
[Wrong Quotes]

### ISSUE THREAD

**Issue by GalloDaSballo** [GalloDaSballo/fair-selling#26]
Something off with UniV3 quote

Pricer is new one (V3)
```
pricer.findOptimalSwap("0xdef1ca1fb7fbcdc777520aa7f396b4e015f497ab", lenient.WETH(), 12209903493709471347595)
(3, 1791493380734586018, (), ())
```

Lenient is old one (V2)
```
>>> lenient.findOptimalSwap("0xdef1ca1fb7fbcdc777520aa7f396b4e015f497ab", lenient.WETH(), 12209903493709471347595)
(5, 965625530951028714, (), ())
```

**Comment by rayeaster** [comment]
> Something off with UniV3 quote
> 
> Pricer is new one (V3)
> 
> ```
> pricer.findOptimalSwap("0xdef1ca1fb7fbcdc777520aa7f396b4e015f497ab", lenient.WETH(), 12209903493709471347595)
> (3, 1791493380734586018, (), ())
> ```
> 
> Lenient is old one (V2)
> 
> ```
> >>> lenient.findOptimalSwap("0xdef1ca1fb7fbcdc777520aa7f396b4e015f497ab", lenient.WETH(), 12209903493709471347595)
> (5, 965625530951028714, (), ())
> ```

I am working on it. thanks for the catching up

**Comment by GalloDaSballo** [comment]
Addressed
