### ISSUE TITLE
feat: automatically set emissions schedule when emitting to tree

### ISSUE THREAD

**Issue by jorijnsmit** [GalloDaSballo/fair-selling#3]
on both `swapCVXTobveCVXAndEmit` and `emitBadger`, when tokens are sent to the tree, the emissions schedule could be set automatically and atomically. this reduces human errors and trust.

- BribesProcessor needs permission to set schedule
- implement calling `setUnlockSchedule` on transfer to tree. see https://github.com/Badger-Finance/badger-multisig/blob/eb27eb035878264d41ab368e1d63306da32a61da/scripts/emissions/bribes_emissions.py#L45-L68 . will need to grab current end date, set it to new start date, and add 14 days for the end date.

**Comment by GalloDaSballo** [comment]
Solved by #4
